---
deployment:
  tasks:
    - export PROJECT=/home/awdp3382/repositories/lokabirin
    - export DEPLOYPATH=/home/awdp3382/public_html/lokabirin
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/cp -r $PROJECT/public/* $DEPLOYPATH
